import 'package:hive/hive.dart';

part 'node.g.dart'; // This will be generated by Hive

@HiveType(typeId: 0)
class Recipe extends HiveObject {
  @HiveField(0)
  String name;

  @HiveField(1)
  List<String> ingredients;

  @HiveField(2)
  List<StepScenario> stepScenarios;

  Recipe({
    required this.name,
    required this.ingredients,
    required this.stepScenarios,
  });
}

@HiveType(typeId: 1)
class StepScenario extends HiveObject {
  @HiveField(0)
  String question;

  @HiveField(1)
  List<String> options;

  @HiveField(2)
  int? correctOptionIndex;

  @HiveField(3)
  bool isFlexible;

  StepScenario({
    required this.question,
    required this.options,
    this.correctOptionIndex, // Optional now
    this.isFlexible = false, // Default to false
  });
}